### ISSUE TITLE
Story intro and tutorial battle

### ISSUE THREAD

**Issue by sladesamuel** [amber-falcon-games/triple-triad#61]
Start building out the story mode of the game, which should teach the player how to play the game.

# Tasks
- [x] New game -> intro
- [x] Dialogue with Quistis
  - [x] Show flashing down arrow at the end of each page of dialogue
  - [x] Handle click on page to go to the next dialogue entry
- [x] Play Balamb Garden music
- [x] After intro dialogue, go into tutorial battle with predefined cards
- [x] Rebuild battle system
- [x] Hook up tutorial battle from intro scene
- [x] Flesh out guided battle
  - [x] Predefined moves
  - [x] Predefined slot placement
  - [x] Dialogue instructions
  - [x] Show Quistis on battle
- [x] Raise event when battle is complete (i.e. when board is full) and handle in End Game component
- [x] Skip card exchange scene - go back to tutorial dialogue instead
- [x] Complete guided tutorial battle
